### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by UdoSL** [treolabs/treocore#340]
Installation still not clear.
Which Linux distribution?

Pl. give examples.
Pl. show step by step.

And/or kindly  provide virtual image.

Pl. note that you may have a distribution, system configuration setting in which it may work right away. Not so for others.

Also - if needed - which mysql configuration is necessary? Where is location / configuration file for credentials / database.

**Comment by hgpit** [comment]
Hello,

We have recently installed it on a Google GCP instance of CentOS 7 without any issues. I will post an overview of the configuration/installation process if you like.
