### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by hgpit** [treolabs/treocore#361]
Hi Is it possible to request a minor feature?

We are brand new with TreoPIM (currently using 3.7.4 without any extensions*), and hoping to have it replace our LAMP-based in-house MDM. What we are struggling with, is the data import feature.

Take '**product categories**', for example.

It took me probably 3 hours of trial and error to get some data imported here into a single entity. Only by manually creating some records via the GUI, and observing the data validation/filtering TreoPIM does, and by logging into MariaDB's CLI and inspecting the actual '**category**' table, did I find the clues.

What we would like to see added into TreoPIM's GUI import:

- When you are mapping your source's fields to the target entity's, can you highlight which entity fields are compulsory/required?
- Compulsory fields should always be added to the field-mapping list - so it's obvious straight away if you can't satisfy them from your data source.
- '**ID**': it looks like you don't want users to import their own '**ID**'s. We assumed this would be an INT field (based on experience with other MDM's and ecommerce platforms). After inspecting the DB, TreoPIM uses some type of 24 character hash. Can you make it more obvious from the importer GUI that this is a TreoPIM-defined field, so the user should only be including it in their data source if it's to update existing records?
- Please make it so that a data source field can be mapped to multiple entity fields. In the case of '**product categories**' (for instance), TreoPIM makes the **name** field of ALL enabled languages compulsory. Which means we can only import data if we have all languages translated (and thus a separate field for each language in our source (eg: nameFrFr, nameDeDe. etc).
It would be good to either have TreoPIM not make alternate languages compulsory (and use a fallback system where the default/primary field is used in the absence of the required country's). If this is not possible, we think a quick fix would simply be to allow the user to configure their '**name**' field (in their source data) to map to multiple target language fields. (we think it's best to have '**Italian**' descriptions imported/displayed as 'English', than not imported/displayed at all).
- DB Table.Field: '**category.code**': It looks like we only finally got our '**category**' data source to import, once we realized that the '**code**' field value has to be lowercase. But the data importer never alerts you to this. It just silently fails. Is it possible TreoPIM can provide some (or any!) feedback on why data is not being imported? We assume it's failing some internal validation check, which can surely be reported back to the user?

Despite these suggestions, we really love what we've seen from TreoPIM so far, and are crossing our fingers tightly that this can be our organization's choice of PIM/MDM going forward.

Keep up the good work!

Kind regards

*We have ordered our first extension, just awaiting support to activate it

**Comment by TetianaZahaietska** [comment]
Hello hgl-it,
You need a module Import Feeds for this. Please contact our support team to get more information about the module and purchase it.
