### ISSUE TITLE
Unable to import category with product

### ISSUE THREAD

**Issue by hgpit** [treolabs/treocore#362]
TreoPIM v3.7.4.

Trying to import/update a product's 'category' via the GUI importer.

We have tried including the category **Code**, the category **Name** and even the category **ID** in our products source file, and mapping it to '**category**' in the TreoPIM field list... but nothing.

The import process completes and all fields are updated/created, except for the **category** field.

Just how do we import the **category** field?!

**Comment by TetianaZahaietska** [comment]
Hello hgpit,
You need a module Import Feeds for this. Please contact our support team to get more informations about the module and purchase it.

**Comment by hgpit** [comment]
It would be nice if the front-end alerted the user to this. I have wasted a lot of valuable time trying to get this to work.

**Comment by TetianaZahaietska** [comment]
Thank you for pointing that out, we will take it into account.
