### ISSUE TITLE
Errors when opening the non-existent entity page

### ISSUE THREAD

**Issue by rratsun** [treolabs/treocore#448]
1. Go to the http://treopim.zinit1.com/#Composer/list page
2. Remove the PIM module
3. After removing the module, open the Product page, insert /#Product in the url
Current result: When you go to the non-existent entity page, there are errors in the console - https://screen.treotest.com/i.rybachok/2019-07-23_09-54-09.jpg
Afrer refreshing the page, the 404 error is displayed, but errors in the console still remain - https://screen.treotest.com/i.rybachok/2019-07-23_09-58-41.jpg
Expected result: If such entity doesn't exist in your system, the 404 error is displayed and there are no errors in the console.

**Comment by irybachok** [comment]
1. Open the page http://treopim.zinit1.com/#Composer/list
2. Remove the module PIM
3. After removing the module, open the Product page, insert /#Product in the url
Actual result: When you go to the entity page, which doesn't exist in your system, there are errors in the console - https://screen.treotest.com/i.rybachok/2019-07-23_09-54-09.jpg
Afrer refreshing the page, the 404 error is displayed, but errors in the console still remain - https://screen.treotest.com/i.rybachok/2019-07-23_09-58-41.jpg
Expected result: If such entity doesn't exist in your system, the 404 error is displayed and there are no errors in the console.
