### ISSUE TITLE
Bug in checking version

### ISSUE THREAD

**Issue by brij1976** [treolabs/treocore#475]
function prepareVersion(string $version, bool $patch = false): ?string in installer.php fails for mysql version 8.0.17

Fixed by using isset instead of !empty

**Comment by r-zablodskiy** [comment]
Hello, @brij1976. We did not find any such error after testing. Please, specify your php and mysql versions.

**Comment by rratsun** [comment]
Yes, you are right. Thanks a lot. We already fix it in 3.22.3.
